# Generated by Django 3.2.7 on 2021-09-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210915_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
